version: '2'
services:
    kanhome-app:
        image: kanhome
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://kanhome-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=KanHome
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    kanhome-mongodb:
        extends:
            file: mongodb.yml
            service: kanhome-mongodb
